//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baozipayment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.paypal.com/cgi-bin/webscr")]
        public string PaypalPaymentVerificationURL {
            get {
                return ((string)(this["PaypalPaymentVerificationURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"(PLEASE DO NOT REPLY TO THIS EMAIL)

Hey {0},

Thanks a lot for your interests in Baozi mock interview!

Your mock interview includes three rounds of 45 min mock interview + 30 min debrief session. We will be speaking to you with audio Skype call and online coding.

Next step: (Please send email to baozitraining@outlook.com, DO NOT REPLY TO THIS EMAIL)
1) Please send us a few times that works for you. Usually Tuesday evening (6pm to 10pm PST/PDT) is our default interview time, we could make exceptions if this absolutely doesn't work for you. We will confirm with our interviewers for their availability and get back to you 2 -3 days afterwards. All of our interviewers are currently working fulltime at well known IT companies. Thanks for your understanding. 
2) Please send us your resume.
3) Please provide us your Skype ID, [Please register one if you don't have it]. A phone number just in case.
4) Please stay at a place that has decent network connection, we will be Skype audio chatting and do online coding.
5) By default, 3 rounds are all coding. If you need system design, please let us know how many coding and system design you want. 

We appreciate your business and good luck on your interviews!

Best,
Baozi Team")]
        public string SdeMockInterviewEmailTemplates {
            get {
                return ((string)(this["SdeMockInterviewEmailTemplates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Action Required] Welcome to Baozi Training Mock Interview")]
        public string SdeMockInterviewEmailTitle {
            get {
                return ((string)(this["SdeMockInterviewEmailTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<html>\r\n<head>\r\n<title>Weekend Class Payment Succeed</title>\r\n</head>\r\n<body>\r\n<p" +
            " align=\"center\" style=\"color: #FF0000\">This is an auto generated message, please" +
            " do NOT reply to the sender.</p>\r\n\r\n<p>\r\nHi {0}, \r\n</p>\r\n\r\n<p>\r\nThanks a lot for" +
            " you interests in Baozi Training\'s weekend algorithm session. We have received y" +
            "our payment and please follow the below items\r\n</p>\r\n<ol>\r\n<li> Please send us y" +
            "our name, email address and WeChat ID (optional) to <a href=\"mailto:baozitrainin" +
            "g@outlook.com\">baozitraining@outlook.com</a> </li>\r\n\r\n<li> Please confirm the da" +
            "tes of the classes: 03/26/2016, 03/27/2016 (from 10am to 2pm PST) </li>\r\n\r\n<li> " +
            "Please share this confirmation email with your friends if you purchased this ser" +
            "vice together . </li>\r\n\r\n<li> We will send you the links to our live webcast and" +
            " on 03/25/2016. For course outline and FAQs, please refer to <a href=\"http://bao" +
            "zitraining.org/#weekend_class\">http://baozitraining.org/#weekendclass/</a> For c" +
            "ourse slides and other materials, we will send it after the class is over. </li>" +
            "\r\n\r\n<li> We will have an algorithm discussion group. please send questions to \r\n" +
            "<a href=\"mailto:baozidiscussion@googlegroups.com\">baozidiscussion@googlegroups.c" +
            "om</a> </li>\r\n\r\n<li> If you prefer to receive the latest interview qustions/tips" +
            ", please subscribe to our WeChat (baozitraining) \r\n(scan QR code bellow) or like" +
            " like our Facebook page <a href=\"https://www.facebook.com/baozitraining/\">https:" +
            "//www.facebook.com/baozitraining/</a> </li>\r\n\r\n<li>What is your current algorith" +
            "m confident level? [Not confident, So so, Very confident]. Have you started prac" +
            "ticing problem solving using online judge, E.g., Leetcode.com? If so, what is yo" +
            "ur current progress? </li>\r\n\r\n<li> For any issues or questions, please feel free" +
            " to contact <a href=\"mailto:baozitraining@outlook.com\">baozitraining@outlook.com" +
            "</a></li>\r\n</ol>\r\n\r\n\r\n<table border=\"0\">\r\n<tr align=\"center\"><td><img width=\"150" +
            "\" height=\"150\" alt=\"open this link if you cannot see the QR code http://baozitra" +
            "ining.org/static/media/logo/Baozi_weixin.jpg\" src=\"http://baozitraining.org/stat" +
            "ic/media/logo/Baozi_weixin.jpg\"/></td></tr>\r\n<tr><td align=\"center\">baozi wechat" +
            " page</td></tr>\r\n</table>\r\n\r\n\r\n<p>\r\nSit back, relax and enjoy our courses! \r\n</p" +
            ">\r\n<p>\r\nThanks,<br>\r\nBaozi Team\r\n</p>\r\n</body>\r\n\r\n</html>")]
        public string OnlineClassEmailTemplates {
            get {
                return ((string)(this["OnlineClassEmailTemplates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Action Required] Welcome to baozi weekend class")]
        public string OnlineClassEmailTitle {
            get {
                return ((string)(this["OnlineClassEmailTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SdeMockInterviewEmailIsHtml {
            get {
                return ((bool)(this["SdeMockInterviewEmailIsHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OnlineClassEmailIsHtml {
            get {
                return ((bool)(this["OnlineClassEmailIsHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Action Required] Welcome to baozi weekend coding test")]
        public string OnlineTestEmailTitle {
            get {
                return ((string)(this["OnlineTestEmailTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"(please do NOT reply to this email)

Hey {0},

Thanks a lot for your interests in Baozi weekend coding test!

We provide weekend coding test service. It includes coding exams (during sat. and sun. morning) and question analysis (during sat. and sun. afternoon). All submitted student answers will be carefully reviewed and scored.

Next step:
1) Please confirm that the time is Saturday & Sunday, Jan 23 2016 - Jan 24 2016, 9am - 5pm PST.
2) Please send email to baozitraining@outlook.com, with title ""register weekend coding test"", payment transcript id and your resume.
3) Please share this information with your group members if you bought this service together.
4) Please stay at a place that has decent network connection, we will be video chatting and do online coding.
5) Follow our wechat ""baozitraining"" for more useful IT interview tricks.

We will send you an email with links to join online coding test meeting by the end of Jan 22 2016. Please relax and be patient.
If you have any other questions, please feel free to send email to baozitraining@outlook.com .

We appreciate your business  and good luck on your coding test!

Best,
Baozi Team")]
        public string OnlineTestEmailTemplates {
            get {
                return ((string)(this["OnlineTestEmailTemplates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnlineTestEmailIsHtml {
            get {
                return ((bool)(this["OnlineTestEmailIsHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Welcome to baozi weekend online Judge")]
        public string OnlineJudgeEmailTitle {
            get {
                return ((string)(this["OnlineJudgeEmailTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"(please do NOT reply to this email)

Hey {0},

Thanks a lot for your interests in Baozi weekend coding online judge!

It is a completely new challange, yet completely entertaining and completely free!

Please confirm that the time is Saturday & Sunday, Jan 23 2016 - Jan 24 2016, 9am - 5pm PST.
And we will send you the link to the online judge by the end of Jan 22 2016.

Also, you will always get an option to purchase classes when you are ready to dig into it.

Follow our wechat ""baozitraining"" for more useful IT interview tricks.
If you have any other questions, please feel free to send email to baozitraining@outlook.com .

Happy Coding!

Best,
Baozi Team")]
        public string OnlineJudgeEmailTemplates {
            get {
                return ((string)(this["OnlineJudgeEmailTemplates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnlineJudgeEmailIsHtml {
            get {
                return ((bool)(this["OnlineJudgeEmailIsHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NonSdeMockInterviewEmailIsHtml {
            get {
                return ((bool)(this["NonSdeMockInterviewEmailIsHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"(PLEASE DO NOT REPLY TO THIS EMAIL)

Hey {0},

Thanks a lot for your interests in Baozi mock interview!

Your mock interview includes one round of 45 min mock interview + 30 min debrief session. We will be speaking to you with audio Skype call and online coding.

Next step: (Please send email to baozitraining@outlook.com, DO NOT REPLY TO THIS EMAIL)
1) Please send us a few times that works for you. Usually Tuesday evening (6pm to 10pm PST/PDT) is our default interview time, we could make exceptions if this absolutely doesn't work for you. We will confirm with our interviewers for their availability and get back to you 2 -3 days afterwards. All of our interviewers are currently working fulltime at well known IT companies. Thanks for your understanding. 
2) Please send us your resume.
3) Please provide us your Skype ID, [Please register one if you don't have it]. A phone number just in case.
4) Please stay at a place that has decent network connection, we will be Skype audio chatting and do online coding.
5) Please let us know if you have any special requirement regarding the interviews, for example, any target company? Coding or System Design? We will try our best to match it.

We appreciate your business and good luck on your interviews!

Best,
Baozi Team")]
        public string NonSdeMockInterviewEmailTemplates {
            get {
                return ((string)(this["NonSdeMockInterviewEmailTemplates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Action Required] Welcome to Baozi Training Mock Interview")]
        public string NonSdeMockInterviewEmailTitle {
            get {
                return ((string)(this["NonSdeMockInterviewEmailTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PremiumSdeMockInterviewEmailIsHtml {
            get {
                return ((bool)(this["PremiumSdeMockInterviewEmailIsHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(PLEASE DO NOT REPLY TO THIS EMAIL)\r\n\r\nHey {0},\r\n\r\nThanks a lot for your interest" +
            "s in Baozi premium mock interview!\r\n\r\nYour mock interview includes three rounds " +
            "of 45 min mock interview + 30 min debrief session, a resume revision and best ef" +
            "fort refer program. We will be speaking to you with audio Skype call and online " +
            "coding.\r\n\r\nNext step: (Please send email to baozitraining@outlook.com, DO NOT RE" +
            "PLY TO THIS EMAIL)\r\n1) Please send us a few times that works for you. Usually Tu" +
            "esday evening (6pm to 10pm PST/PDT) is our default interview time, we could make" +
            " exceptions if this absolutely doesn\'t work for you. We will confirm with our in" +
            "terviewers for their availability and get back to you 2 -3 days afterwards. All " +
            "of our interviewers are currently working fulltime at well known IT companies. T" +
            "hanks for your understanding. \r\n2) Please send us your resume. Please cc qiangin" +
            "terview@gmail.com, teacher Qiang will help you with resume.\r\n3) Please provide u" +
            "s your Skype ID, [Please register one if you don\'t have it]. A phone number just" +
            " in case.\r\n4) Please stay at a place that has decent network connection, we will" +
            " be Skype audio chatting and do online coding.\r\n5) By default, 3 rounds are all " +
            "coding. If you need system design, please let us know how many coding and system" +
            " design you want. \r\n6) For referral program\r\n6.1)\r\nWe collaborate with lingoffer" +
            ".com, please register. We will let them you are Baozi student so you can get ref" +
            "erred more times than normal users. \r\n6.2)\r\nPlease attach your latest revised re" +
            "sume. The majority of the listed companies need a job id to refer you in the sys" +
            "tem. So please go to those companies website, find 1 or 2 job ids that you are m" +
            "ost interested in, and send an email and your resume to \r\nbaozirefer@googlegroup" +
            "s.com\r\nWe can refer the below companies, however, it also heavily depends on eac" +
            "h company\'s head count. We will give our best try if you did very well in mock i" +
            "nterviews, but unfortunately we cannot guarantee anything (as a matter of fact, " +
            "nobody can guarantee this, if somebody says they can, please rethink). \r\n\r\n\r\n\r\n\r" +
            "\nWe appreciate your business and good luck on your interviews!\r\n\r\nBest,\r\nBaozi T" +
            "eam")]
        public string PremiumSdeMockInterviewEmailTemplates {
            get {
                return ((string)(this["PremiumSdeMockInterviewEmailTemplates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Action Required] Welcome to Baozi Training Mock Interview")]
        public string PremiumSdeMockInterviewEmailTitle {
            get {
                return ((string)(this["PremiumSdeMockInterviewEmailTitle"]));
            }
        }
    }
}
